name: sistema-inmobiliario
services:
- name: web
  source_dir: /
  github:
    repo: tu-usuario/sistema-inmobiliario
    branch: main
  run_command: gunicorn --bind 0.0.0.0:$PORT wsgi:application
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: FLASK_ENV
    value: production
  - key: PYTHONPATH
    value: "." 
    value: "." 